### ISSUE TITLE
`tei:rs` instead of `tei:orgName` on purpose or by mistake?

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/Hermann-Bahr_Arthur-Schnitzler#3]
https://github.com/acdh-oeaw/Hermann-Bahr_Arthur-Schnitzler/blob/d015ef0d4b4b312c0ac32eed566053e416a88337/app/data/indices/listorg.xml#L50

**Comment by martinantonmueller** [comment]
Mistake it is! I'll fix it!
