### ISSUE TITLE
`<title level="a">` for index-files

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/Hermann-Bahr_Arthur-Schnitzler#4]
wäre es möglich, bei den Register Dateien im title stmt 
https://github.com/acdh-oeaw/Hermann-Bahr_Arthur-Schnitzler/blob/03f0d154cc0f9ce6f59d840b1dd8e3ced159ba0e/app/data/indices/listplace.xml#L11

ein `<title level="a">` etwa `<title level="a">Regsiter der erwähten Orte`</title> oder so einzufügen?

Dieser Title könnte dann für den entsprechenden ARCHE Metadaten eintrag verwendet werden

**Comment by martinantonmueller** [comment]
Hätte ich eine saubere Merge-Message gemacht, wäre das jetzt automatisch geschlossen. So aber muss ich das händisch tun. Ich lern’s wohl nie.
